# Project : Deeper understanding of how neural networks learn
## Objective : To go through how the matrix changes its shape and make its way through the layers to the final output layer and how updation of weights effects the overall loss and prediction power of the network !

### The codes have been highly influenced by the one given on the Andrew Trask's blog page


```
references
```
[Andrew Trask's code for neural network](https://iamtrask.github.io/2015/07/12/basic-python-network/)


### packages import

In [0]:
import numpy as np

### Function for training the network made of 3 input nodes and 1 output node

In [0]:
def feed_forward_backpropogation_train(n, X, y, weights_input_to_hidden, weights_hidden_to_output, shapes = False):
  if shapes == True:
    for j in range(n):
      print("inside the loop....")
      h1 = 1/(1+np.exp(-(np.dot(X,weights_input_to_hidden))))
      print(f"first output shape : {X.shape} x {weights_input_to_hidden.shape} =  {h1.shape}")
      print(f"shape of h1 : {h1.shape}")
      print(f"shape of weights_hidden_to_output : {weights_hidden_to_output.shape}")
      output = 1/(1+np.exp(-(np.dot(h1,weights_hidden_to_output))))
      print(f"second outupt shape {h1.shape} x {weights_hidden_to_output.shape} = {output.shape}")
      print(f"predicted :")
      print(output)
      print()
      output_delta = (y - output)*(output*(1-output))
      h1_delta = output_delta.dot(weights_hidden_to_output.T) * (h1 * (1-h1))
      weights_hidden_to_output += h1.T.dot(output_delta)
      weights_input_to_hidden += X.T.dot(h1_delta)
  else:
    for j in range(n):
      # feedforward pass
      h1 = 1/(1+np.exp(-(np.dot(X,weights_input_to_hidden))))
      output = 1/(1+np.exp(-(np.dot(h1,weights_hidden_to_output))))
      # backpropogation of error 
      output_delta = (y - output)*(output*(1-output))
      h1_delta = output_delta.dot(weights_hidden_to_output.T) * (h1 * (1-h1))
      # updation of weights
      weights_hidden_to_output += h1.T.dot(output_delta)
      weights_input_to_hidden += X.T.dot(h1_delta)
  return weights_input_to_hidden, weights_hidden_to_output

### Let's understand the code one by one by actually seeing the shapes of matrix as they go from layer to layer and how they are changed in the way....

In [0]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
print("X (training examples)")
print(X)
print(f"shape X: {X.shape}")
y = np.array([[0,1,1,0]]).T
print("Y (actual target)")
print(y)
print(f"shape of Y : {y.shape}")
weights_input_to_hidden = 2*np.random.random((3,4)) - 1
print("weights initialized from input to hidden:")
print(weights_input_to_hidden)
print(f"shape of weights_input_to_hidden: {weights_input_to_hidden.shape}")
weights_hidden_to_output = 2*np.random.random((4,1)) - 1
print("weights iniatialized from hidden to output:")
print(weights_hidden_to_output)
print(f"shape of weights_hidden_to_output: {weights_hidden_to_output.shape}")

print("Let's play with one time pass and check the shapes of matrix data as they pass from input to output:")
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(1, X, y, weights_input_to_hidden, weights_hidden_to_output, True)


print("new weights from input to hidden")
print(weights_input_to_hidden)
print("new wegiths from hidden to output")
print(weights_hidden_to_output)

print()
print("Let's now iterate more and check how these weights get updated")
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(10000, X, y, weights_input_to_hidden, weights_hidden_to_output)


print("new weights from input to hidden")
print(weights_input_to_hidden)
print("new weights from hidden to output")
print(weights_hidden_to_output)

X (training examples)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
shape X: (4, 3)
Y (actual target)
[[0]
 [1]
 [1]
 [0]]
shape of Y : (4, 1)
weights initialized from input to hidden:
[[-0.95248212  0.94801853 -0.06155864 -0.39234065]
 [ 0.09271474  0.07193927  0.71815955  0.63630801]
 [-0.27803125 -0.27031507  0.32315005 -0.38833101]]
shape of weights_input_to_hidden: (3, 4)
weights iniatialized from hidden to output:
[[ 0.19642532]
 [ 0.45506969]
 [ 0.56397485]
 [-0.62344138]]
shape of weights_hidden_to_output: (4, 1)
Let's play with one time pass and check the shapes of matrix data as they pass from input to output:
inside the loop....
first output shape : (4, 3) x (3, 4) =  (4, 4)
shape of h1 : (4, 4)
shape of weights_hidden_to_output : (4, 1)
second outupt shape (4, 4) x (4, 1) = (4, 1)
predicted :
[[0.58827215]
 [0.58924374]
 [0.61515074]
 [0.61715719]]

new weights from input to hidden
[[-0.95461549  0.94281835 -0.06524971 -0.3819703 ]
 [ 0.09229036  0.06867838  0.7126517   0.64365783]


### Function to make a single pass through the network with updated weights

In [0]:
def run_network(X, weights_input_to_hidden, weights_hidden_to_output):
      h1 = 1/(1+np.exp(-(np.dot(X,weights_input_to_hidden))))
      output = 1/(1+np.exp(-(np.dot(h1,weights_hidden_to_output))))
      return output

### Defining error (here we take mean squared error)

In [0]:
def MSE(y, Y):
  return np.mean((y - Y)**2)

### Here we actually see how increasing the training of network decreases overall loss but mind it this is training loss !
### Actual testing loss is the one which is over unseen data !

In [0]:
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(10000, X, y, weights_input_to_hidden, weights_hidden_to_output)
error = MSE(y, run_network(X, weights_input_to_hidden, weights_hidden_to_output))
print(error)

3.84720358988406e-05


In [0]:
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(20000, X, y, weights_input_to_hidden, weights_hidden_to_output)
error = MSE(y, run_network(X1, weights_input_to_hidden, weights_hidden_to_output))
print(error)

2.268337988998213e-05


In [0]:
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(40000, X, y, weights_input_to_hidden, weights_hidden_to_output)
error = MSE(y, run_network(X, weights_input_to_hidden, weights_hidden_to_output))
print(error)

1.241752187774674e-05


In [0]:
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(100000, X, y, weights_input_to_hidden, weights_hidden_to_output)
error = MSE(y, run_network(X, weights_input_to_hidden, weights_hidden_to_output))
print(error)

5.803759988643886e-06
