# Project :Deeper understanding of how neural networks learn (I)
## Objective : To go through how the matrix changes its shape and make its way through the layers to the final output layer and how updation of weights effects the overall loss and prediction power of the network !

### The codes have been highly influenced by the one given on the Andrew Trask's blog page


The following is like a walk-through tutorial, so i hope you enjoy !

```
references
```
[Andrew Trask's code for neural network](https://iamtrask.github.io/2015/07/12/basic-python-network/)


### packages import

In [0]:
import numpy as np

### Function for training the network made of 3 input nodes and 1 output node

In [0]:
# function for feedforward and backpropogation step 
#if shapes = True, that means we want to print the shapes as well otherwise no shape will be printed, only pass will be done.
def feed_forward_backpropogation_train(n, X, y, weights_input_to_hidden, weights_hidden_to_output, shapes = True):
    '''
    n : number of iterations
    X : Input data matrix 
    y : actual target (label)
    weights_input_to_hidden : weights matrix from input to hidden layer
    weights_hidden_to_output : weights matrix from hidden to output layer
    shapes : if shapes required to be printed or not 
    '''
    if shapes == True:
        for j in range(n):
            print("inside the loop....")
            h1 = 1/(1+np.exp(-(np.dot(X,weights_input_to_hidden))))
            print(f"first output shape : {X.shape} x {weights_input_to_hidden.shape} =  {h1.shape}")
            print(f"shape of h1 : {h1.shape}")
            print(f"shape of weights_hidden_to_output : {weights_hidden_to_output.shape}")
            output = 1/(1+np.exp(-(np.dot(h1,weights_hidden_to_output))))
            print(f"second outupt shape {h1.shape} x {weights_hidden_to_output.shape} = {output.shape}")
            print(f"predicted :")
            print(output)
            print()
            output_delta = (y - output)*(output*(1-output))
            h1_delta = output_delta.dot(weights_hidden_to_output.T) * (h1 * (1-h1))
            weights_hidden_to_output += h1.T.dot(output_delta)
            weights_input_to_hidden += X.T.dot(h1_delta)
    else:
        for j in range(n):
            # feedforward pass
            h1 = 1/(1+np.exp(-(np.dot(X,weights_input_to_hidden))))
            output = 1/(1+np.exp(-(np.dot(h1,weights_hidden_to_output))))
            # backpropogation of error 
            output_delta = (y - output)*(output*(1-output))
            h1_delta = output_delta.dot(weights_hidden_to_output.T) * (h1 * (1-h1))
            # updation of weights
            weights_hidden_to_output += h1.T.dot(output_delta)
            weights_input_to_hidden += X.T.dot(h1_delta)
    return weights_input_to_hidden, weights_hidden_to_output

### Let's understand the code one by one by actually seeing the shapes of matrix as they go from layer to layer and how they are changed in the way....

Here we are using a neural network consisting of one hidden layer(containing one node) and one output layer (including input layer which we don't necessarily count as a layer)

In [28]:
# Here we start our analysis by taking input examples and outputs.
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
print("X (training examples)")
print(X)
print(f"shape X: {X.shape}")
y = np.array([[0,1,1,0]]).T
print("Y (actual target)")
print(y)
print(f"shape of Y : {y.shape}")
weights_input_to_hidden = 2*np.random.random((3,4)) - 1
print("weights initialized from input to hidden:")
print(weights_input_to_hidden)
print(f"shape of weights_input_to_hidden: {weights_input_to_hidden.shape}")
weights_hidden_to_output = 2*np.random.random((4,1)) - 1
print("weights iniatialized from hidden to output:")
print(weights_hidden_to_output)
print(f"shape of weights_hidden_to_output: {weights_hidden_to_output.shape}")

print("Let's play with one time pass and check the shapes of matrix data as they pass from input to output:")
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(1, X, y, weights_input_to_hidden, weights_hidden_to_output, True)


print("new weights from input to hidden")
print(weights_input_to_hidden)
print("new weights from hidden to output")
print(weights_hidden_to_output)

print()
print("Let's now iterate more and check how these weights get updated")
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(10000, X, y, weights_input_to_hidden, weights_hidden_to_output, False)


print("new weights from input to hidden")
print(weights_input_to_hidden)
print("new weights from hidden to output")
print(weights_hidden_to_output)

X (training examples)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
shape X: (4, 3)
Y (actual target)
[[0]
 [1]
 [1]
 [0]]
shape of Y : (4, 1)
weights initialized from input to hidden:
[[ 0.81782303  0.95969135  0.15655927 -0.16690352]
 [-0.00180481  0.73578928 -0.57032858  0.19066284]
 [ 0.76723382  0.14705598 -0.98890526 -0.56767396]]
shape of weights_input_to_hidden: (3, 4)
weights iniatialized from hidden to output:
[[ 0.5093118 ]
 [-0.74293308]
 [-0.37334562]
 [-0.95113288]]
shape of weights_hidden_to_output: (4, 1)
Let's play with one time pass and check the shapes of matrix data as they pass from input to output:
inside the loop....
first output shape : (4, 3) x (3, 4) =  (4, 4)
shape of h1 : (4, 4)
shape of weights_hidden_to_output : (4, 1)
second outupt shape (4, 4) x (4, 1) = (4, 1)
predicted :
[[0.3784271 ]
 [0.34756135]
 [0.36420226]
 [0.3448391 ]]

new weights from input to hidden
[[ 0.82279962  0.94609927  0.14955591 -0.18036304]
 [ 0.00891509  0.71987164 -0.57365041  0.17392407]


### Function to make a single pass through the network with updated weights

In [0]:
# function to do a single pass run through the network to predict the output 
def run_network(X, weights_input_to_hidden, weights_hidden_to_output):
    '''
    X : input data matrix
    weights_input_to_hidden : weights matrix from input to hidden layer
    weights_hidden_to_output : weights matrix from hidden to output layer
    '''
    h1 = 1/(1+np.exp(-(np.dot(X,weights_input_to_hidden))))
    output = 1/(1+np.exp(-(np.dot(h1,weights_hidden_to_output))))
    return output

### Defining error (here we take [mean squared error](https://en.wikipedia.org/wiki/Mean_squared_error))

In [0]:
# function to calculate the error 
def MSE(y, Y):
    '''
    y : actual label (matrix)
    Y : predicted label (matrix)
    '''
    return np.mean((y - Y)**2)

### Here we actually see how increasing the training of network decreases overall loss but mind it this is training loss !
### Actual testing loss is the one which is over unseen data !

In [40]:
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(10000, X, y, weights_input_to_hidden, weights_hidden_to_output, False)
error = MSE(y, run_network(X, weights_input_to_hidden, weights_hidden_to_output))
print(error)

4.0107463780298154e-06


In [41]:
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(20000, X, y, weights_input_to_hidden, weights_hidden_to_output, False)
error = MSE(y, run_network(X, weights_input_to_hidden, weights_hidden_to_output))
print(error)

3.640432255734101e-06


In [42]:
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(40000, X, y, weights_input_to_hidden, weights_hidden_to_output, False)
error = MSE(y, run_network(X, weights_input_to_hidden, weights_hidden_to_output))
print(error)

3.067497883744055e-06


In [43]:
weights_input_to_hidden, weights_hidden_to_output = feed_forward_backpropogation_train(100000, X, y, weights_input_to_hidden, weights_hidden_to_output, False)
error = MSE(y, run_network(X, weights_input_to_hidden, weights_hidden_to_output))
print(error)

2.1877647038761036e-06


#### Feel free to explore more as everything is Open Sourced !
